### PR TITLE
Remove string conversion from JsonSerializer, test decoding of Unicode responses

### PR DESCRIPTION
**Pull request by rlucioni**
@jimabramson @clintonb

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by jimabramson** [comment]
@rlucioni this is instead of the previous fix, not in addition to it, right ?

**Comment by rlucioni** [comment]
@jimabramson this is in addition. We need to both specify an encoding and prevent the correctly decoded data from being converted back to a string.

**Comment by jimabramson** [comment]
:+1:

**Comment by rlucioni** [comment]
@clintonb @jimabramson minor addendum to the test, which is now skipped if the installed version of Python is greater than 2.7. Running the test for Python 3 was causing failures on the [open source PR](https://github.com/samgiles/slumber/pull/110).

**Comment by jimabramson** [comment]
:+1:

**Pull request merged**
